// Lab5.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module Lab5 (
		input  wire       clk_clk,       //   clk.clk
		input  wire       reset_reset_n, // reset.reset_n
		output wire [7:0] rgb_rgbs       //   rgb.rgbs
	);

	wire  [31:0] nios_data_manager_awaddr;                              // NIOS:data_manager_awaddr -> mm_interconnect_0:NIOS_data_manager_awaddr
	wire   [1:0] nios_data_manager_bresp;                               // mm_interconnect_0:NIOS_data_manager_bresp -> NIOS:data_manager_bresp
	wire         nios_data_manager_arready;                             // mm_interconnect_0:NIOS_data_manager_arready -> NIOS:data_manager_arready
	wire  [31:0] nios_data_manager_rdata;                               // mm_interconnect_0:NIOS_data_manager_rdata -> NIOS:data_manager_rdata
	wire   [3:0] nios_data_manager_wstrb;                               // NIOS:data_manager_wstrb -> mm_interconnect_0:NIOS_data_manager_wstrb
	wire         nios_data_manager_wready;                              // mm_interconnect_0:NIOS_data_manager_wready -> NIOS:data_manager_wready
	wire         nios_data_manager_awready;                             // mm_interconnect_0:NIOS_data_manager_awready -> NIOS:data_manager_awready
	wire         nios_data_manager_rready;                              // NIOS:data_manager_rready -> mm_interconnect_0:NIOS_data_manager_rready
	wire         nios_data_manager_bready;                              // NIOS:data_manager_bready -> mm_interconnect_0:NIOS_data_manager_bready
	wire         nios_data_manager_wvalid;                              // NIOS:data_manager_wvalid -> mm_interconnect_0:NIOS_data_manager_wvalid
	wire  [31:0] nios_data_manager_araddr;                              // NIOS:data_manager_araddr -> mm_interconnect_0:NIOS_data_manager_araddr
	wire   [2:0] nios_data_manager_arprot;                              // NIOS:data_manager_arprot -> mm_interconnect_0:NIOS_data_manager_arprot
	wire   [1:0] nios_data_manager_rresp;                               // mm_interconnect_0:NIOS_data_manager_rresp -> NIOS:data_manager_rresp
	wire   [2:0] nios_data_manager_awprot;                              // NIOS:data_manager_awprot -> mm_interconnect_0:NIOS_data_manager_awprot
	wire  [31:0] nios_data_manager_wdata;                               // NIOS:data_manager_wdata -> mm_interconnect_0:NIOS_data_manager_wdata
	wire         nios_data_manager_arvalid;                             // NIOS:data_manager_arvalid -> mm_interconnect_0:NIOS_data_manager_arvalid
	wire         nios_data_manager_bvalid;                              // mm_interconnect_0:NIOS_data_manager_bvalid -> NIOS:data_manager_bvalid
	wire         nios_data_manager_awvalid;                             // NIOS:data_manager_awvalid -> mm_interconnect_0:NIOS_data_manager_awvalid
	wire         nios_data_manager_rvalid;                              // mm_interconnect_0:NIOS_data_manager_rvalid -> NIOS:data_manager_rvalid
	wire  [31:0] nios_instruction_manager_awaddr;                       // NIOS:instruction_manager_awaddr -> mm_interconnect_0:NIOS_instruction_manager_awaddr
	wire   [1:0] nios_instruction_manager_bresp;                        // mm_interconnect_0:NIOS_instruction_manager_bresp -> NIOS:instruction_manager_bresp
	wire         nios_instruction_manager_arready;                      // mm_interconnect_0:NIOS_instruction_manager_arready -> NIOS:instruction_manager_arready
	wire  [31:0] nios_instruction_manager_rdata;                        // mm_interconnect_0:NIOS_instruction_manager_rdata -> NIOS:instruction_manager_rdata
	wire   [3:0] nios_instruction_manager_wstrb;                        // NIOS:instruction_manager_wstrb -> mm_interconnect_0:NIOS_instruction_manager_wstrb
	wire         nios_instruction_manager_wready;                       // mm_interconnect_0:NIOS_instruction_manager_wready -> NIOS:instruction_manager_wready
	wire         nios_instruction_manager_awready;                      // mm_interconnect_0:NIOS_instruction_manager_awready -> NIOS:instruction_manager_awready
	wire         nios_instruction_manager_rready;                       // NIOS:instruction_manager_rready -> mm_interconnect_0:NIOS_instruction_manager_rready
	wire         nios_instruction_manager_bready;                       // NIOS:instruction_manager_bready -> mm_interconnect_0:NIOS_instruction_manager_bready
	wire         nios_instruction_manager_wvalid;                       // NIOS:instruction_manager_wvalid -> mm_interconnect_0:NIOS_instruction_manager_wvalid
	wire  [31:0] nios_instruction_manager_araddr;                       // NIOS:instruction_manager_araddr -> mm_interconnect_0:NIOS_instruction_manager_araddr
	wire   [2:0] nios_instruction_manager_arprot;                       // NIOS:instruction_manager_arprot -> mm_interconnect_0:NIOS_instruction_manager_arprot
	wire   [1:0] nios_instruction_manager_rresp;                        // mm_interconnect_0:NIOS_instruction_manager_rresp -> NIOS:instruction_manager_rresp
	wire   [2:0] nios_instruction_manager_awprot;                       // NIOS:instruction_manager_awprot -> mm_interconnect_0:NIOS_instruction_manager_awprot
	wire  [31:0] nios_instruction_manager_wdata;                        // NIOS:instruction_manager_wdata -> mm_interconnect_0:NIOS_instruction_manager_wdata
	wire         nios_instruction_manager_arvalid;                      // NIOS:instruction_manager_arvalid -> mm_interconnect_0:NIOS_instruction_manager_arvalid
	wire         nios_instruction_manager_bvalid;                       // mm_interconnect_0:NIOS_instruction_manager_bvalid -> NIOS:instruction_manager_bvalid
	wire         nios_instruction_manager_awvalid;                      // NIOS:instruction_manager_awvalid -> mm_interconnect_0:NIOS_instruction_manager_awvalid
	wire         nios_instruction_manager_rvalid;                       // mm_interconnect_0:NIOS_instruction_manager_rvalid -> NIOS:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;  // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;    // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest; // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;     // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;       // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;   // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire         mm_interconnect_0_rgbs_avalon_slave_0_chipselect;      // mm_interconnect_0:RGBS_avalon_slave_0_chipselect -> RGBS:chipselect
	wire   [7:0] mm_interconnect_0_rgbs_avalon_slave_0_readdata;        // RGBS:readdata -> mm_interconnect_0:RGBS_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_rgbs_avalon_slave_0_address;         // mm_interconnect_0:RGBS_avalon_slave_0_address -> RGBS:address
	wire         mm_interconnect_0_rgbs_avalon_slave_0_read;            // mm_interconnect_0:RGBS_avalon_slave_0_read -> RGBS:read
	wire         mm_interconnect_0_rgbs_avalon_slave_0_write;           // mm_interconnect_0:RGBS_avalon_slave_0_write -> RGBS:write
	wire   [7:0] mm_interconnect_0_rgbs_avalon_slave_0_writedata;       // mm_interconnect_0:RGBS_avalon_slave_0_writedata -> RGBS:writedata
	wire  [31:0] mm_interconnect_0_nios_dm_agent_readdata;              // NIOS:dm_agent_readdata -> mm_interconnect_0:NIOS_dm_agent_readdata
	wire         mm_interconnect_0_nios_dm_agent_waitrequest;           // NIOS:dm_agent_waitrequest -> mm_interconnect_0:NIOS_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_nios_dm_agent_address;               // mm_interconnect_0:NIOS_dm_agent_address -> NIOS:dm_agent_address
	wire         mm_interconnect_0_nios_dm_agent_read;                  // mm_interconnect_0:NIOS_dm_agent_read -> NIOS:dm_agent_read
	wire         mm_interconnect_0_nios_dm_agent_readdatavalid;         // NIOS:dm_agent_readdatavalid -> mm_interconnect_0:NIOS_dm_agent_readdatavalid
	wire         mm_interconnect_0_nios_dm_agent_write;                 // mm_interconnect_0:NIOS_dm_agent_write -> NIOS:dm_agent_write
	wire  [31:0] mm_interconnect_0_nios_dm_agent_writedata;             // mm_interconnect_0:NIOS_dm_agent_writedata -> NIOS:dm_agent_writedata
	wire         mm_interconnect_0_sram_s1_chipselect;                  // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                    // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [14:0] mm_interconnect_0_sram_s1_address;                     // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                  // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                       // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                   // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                       // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire  [31:0] mm_interconnect_0_nios_timer_sw_agent_readdata;        // NIOS:timer_sw_agent_readdata -> mm_interconnect_0:NIOS_timer_sw_agent_readdata
	wire         mm_interconnect_0_nios_timer_sw_agent_waitrequest;     // NIOS:timer_sw_agent_waitrequest -> mm_interconnect_0:NIOS_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_nios_timer_sw_agent_address;         // mm_interconnect_0:NIOS_timer_sw_agent_address -> NIOS:timer_sw_agent_address
	wire         mm_interconnect_0_nios_timer_sw_agent_read;            // mm_interconnect_0:NIOS_timer_sw_agent_read -> NIOS:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_nios_timer_sw_agent_byteenable;      // mm_interconnect_0:NIOS_timer_sw_agent_byteenable -> NIOS:timer_sw_agent_byteenable
	wire         mm_interconnect_0_nios_timer_sw_agent_readdatavalid;   // NIOS:timer_sw_agent_readdatavalid -> mm_interconnect_0:NIOS_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_nios_timer_sw_agent_write;           // mm_interconnect_0:NIOS_timer_sw_agent_write -> NIOS:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_nios_timer_sw_agent_writedata;       // mm_interconnect_0:NIOS_timer_sw_agent_writedata -> NIOS:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                              // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] nios_platform_irq_rx_irq;                              // irq_mapper:sender_irq -> NIOS:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [DEBUG:rst_n, NIOS:reset_reset, RGBS:reset_n, SRAM:reset, irq_mapper:reset, mm_interconnect_0:NIOS_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                    // rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]
	wire         nios_dbg_reset_out_reset;                              // NIOS:dbg_reset_out_reset -> rst_controller:reset_in1
	wire         rst_controller_001_reset_out_reset;                    // rst_controller_001:reset_out -> NIOS:ndm_reset_in_reset

	altera_avalon_jtag_uart #(
		.readBufferDepth            (64),
		.readIRQThreshold           (8),
		.useRegistersForReadBuffer  (0),
		.useRegistersForWriteBuffer (0),
		.writeBufferDepth           (64),
		.writeIRQThreshold          (8),
		.printingMethod             (0),
		.FIFO_WIDTH                 (8),
		.WR_WIDTHU                  (6),
		.RD_WIDTHU                  (6),
		.write_le                   ("ON"),
		.read_le                    ("ON"),
		.HEX_WRITE_DEPTH_STR        (64),
		.HEX_READ_DEPTH_STR         (64),
		.legacySignalAllow          (0)
	) debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	Lab5_NIOS nios (
		.clk                          (clk_clk),                                             //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                      //               reset.reset
		.platform_irq_rx_irq          (nios_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (rst_controller_001_reset_out_reset),                  //        ndm_reset_in.reset
		.timer_sw_agent_address       (mm_interconnect_0_nios_timer_sw_agent_address),       //      timer_sw_agent.address
		.timer_sw_agent_byteenable    (mm_interconnect_0_nios_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_read          (mm_interconnect_0_nios_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_nios_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_write         (mm_interconnect_0_nios_timer_sw_agent_write),         //                    .write
		.timer_sw_agent_writedata     (mm_interconnect_0_nios_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_waitrequest   (mm_interconnect_0_nios_timer_sw_agent_waitrequest),   //                    .waitrequest
		.timer_sw_agent_readdatavalid (mm_interconnect_0_nios_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.instruction_manager_awaddr   (nios_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (nios_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (nios_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (nios_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (nios_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (nios_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (nios_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (nios_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (nios_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (nios_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (nios_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (nios_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (nios_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (nios_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (nios_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (nios_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (nios_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (nios_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (nios_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (nios_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (nios_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (nios_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (nios_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (nios_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (nios_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (nios_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (nios_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (nios_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (nios_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (nios_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (nios_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (nios_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (nios_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (nios_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (nios_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (nios_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (nios_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (nios_data_manager_rready),                            //                    .rready
		.dm_agent_address             (mm_interconnect_0_nios_dm_agent_address),             //            dm_agent.address
		.dm_agent_read                (mm_interconnect_0_nios_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_nios_dm_agent_readdata),            //                    .readdata
		.dm_agent_write               (mm_interconnect_0_nios_dm_agent_write),               //                    .write
		.dm_agent_writedata           (mm_interconnect_0_nios_dm_agent_writedata),           //                    .writedata
		.dm_agent_waitrequest         (mm_interconnect_0_nios_dm_agent_waitrequest),         //                    .waitrequest
		.dm_agent_readdatavalid       (mm_interconnect_0_nios_dm_agent_readdatavalid),       //                    .readdatavalid
		.dbg_reset_out_reset          (nios_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	customIp rgbs (
		.address    (mm_interconnect_0_rgbs_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_rgbs_avalon_slave_0_chipselect), //               .chipselect
		.read       (mm_interconnect_0_rgbs_avalon_slave_0_read),       //               .read
		.write      (mm_interconnect_0_rgbs_avalon_slave_0_write),      //               .write
		.writedata  (mm_interconnect_0_rgbs_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_rgbs_avalon_slave_0_readdata),   //               .readdata
		.clk        (clk_clk),                                          //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                  //          reset.reset_n
		.rgb_out    (rgb_rgbs)                                          //    conduit_end.rgbs
	);

	Lab5_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	Lab5_mm_interconnect_0 mm_interconnect_0 (
		.NIOS_data_manager_awaddr               (nios_data_manager_awaddr),                              //                NIOS_data_manager.awaddr
		.NIOS_data_manager_awprot               (nios_data_manager_awprot),                              //                                 .awprot
		.NIOS_data_manager_awvalid              (nios_data_manager_awvalid),                             //                                 .awvalid
		.NIOS_data_manager_awready              (nios_data_manager_awready),                             //                                 .awready
		.NIOS_data_manager_wdata                (nios_data_manager_wdata),                               //                                 .wdata
		.NIOS_data_manager_wstrb                (nios_data_manager_wstrb),                               //                                 .wstrb
		.NIOS_data_manager_wvalid               (nios_data_manager_wvalid),                              //                                 .wvalid
		.NIOS_data_manager_wready               (nios_data_manager_wready),                              //                                 .wready
		.NIOS_data_manager_bresp                (nios_data_manager_bresp),                               //                                 .bresp
		.NIOS_data_manager_bvalid               (nios_data_manager_bvalid),                              //                                 .bvalid
		.NIOS_data_manager_bready               (nios_data_manager_bready),                              //                                 .bready
		.NIOS_data_manager_araddr               (nios_data_manager_araddr),                              //                                 .araddr
		.NIOS_data_manager_arprot               (nios_data_manager_arprot),                              //                                 .arprot
		.NIOS_data_manager_arvalid              (nios_data_manager_arvalid),                             //                                 .arvalid
		.NIOS_data_manager_arready              (nios_data_manager_arready),                             //                                 .arready
		.NIOS_data_manager_rdata                (nios_data_manager_rdata),                               //                                 .rdata
		.NIOS_data_manager_rresp                (nios_data_manager_rresp),                               //                                 .rresp
		.NIOS_data_manager_rvalid               (nios_data_manager_rvalid),                              //                                 .rvalid
		.NIOS_data_manager_rready               (nios_data_manager_rready),                              //                                 .rready
		.NIOS_instruction_manager_awaddr        (nios_instruction_manager_awaddr),                       //         NIOS_instruction_manager.awaddr
		.NIOS_instruction_manager_awprot        (nios_instruction_manager_awprot),                       //                                 .awprot
		.NIOS_instruction_manager_awvalid       (nios_instruction_manager_awvalid),                      //                                 .awvalid
		.NIOS_instruction_manager_awready       (nios_instruction_manager_awready),                      //                                 .awready
		.NIOS_instruction_manager_wdata         (nios_instruction_manager_wdata),                        //                                 .wdata
		.NIOS_instruction_manager_wstrb         (nios_instruction_manager_wstrb),                        //                                 .wstrb
		.NIOS_instruction_manager_wvalid        (nios_instruction_manager_wvalid),                       //                                 .wvalid
		.NIOS_instruction_manager_wready        (nios_instruction_manager_wready),                       //                                 .wready
		.NIOS_instruction_manager_bresp         (nios_instruction_manager_bresp),                        //                                 .bresp
		.NIOS_instruction_manager_bvalid        (nios_instruction_manager_bvalid),                       //                                 .bvalid
		.NIOS_instruction_manager_bready        (nios_instruction_manager_bready),                       //                                 .bready
		.NIOS_instruction_manager_araddr        (nios_instruction_manager_araddr),                       //                                 .araddr
		.NIOS_instruction_manager_arprot        (nios_instruction_manager_arprot),                       //                                 .arprot
		.NIOS_instruction_manager_arvalid       (nios_instruction_manager_arvalid),                      //                                 .arvalid
		.NIOS_instruction_manager_arready       (nios_instruction_manager_arready),                      //                                 .arready
		.NIOS_instruction_manager_rdata         (nios_instruction_manager_rdata),                        //                                 .rdata
		.NIOS_instruction_manager_rresp         (nios_instruction_manager_rresp),                        //                                 .rresp
		.NIOS_instruction_manager_rvalid        (nios_instruction_manager_rvalid),                       //                                 .rvalid
		.NIOS_instruction_manager_rready        (nios_instruction_manager_rready),                       //                                 .rready
		.clk_0_clk_clk                          (clk_clk),                                               //                        clk_0_clk.clk
		.NIOS_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // NIOS_reset_reset_bridge_in_reset.reset
		.DEBUG_avalon_jtag_slave_address        (mm_interconnect_0_debug_avalon_jtag_slave_address),     //          DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write          (mm_interconnect_0_debug_avalon_jtag_slave_write),       //                                 .write
		.DEBUG_avalon_jtag_slave_read           (mm_interconnect_0_debug_avalon_jtag_slave_read),        //                                 .read
		.DEBUG_avalon_jtag_slave_readdata       (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                                 .readdata
		.DEBUG_avalon_jtag_slave_writedata      (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                                 .writedata
		.DEBUG_avalon_jtag_slave_waitrequest    (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                                 .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect     (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  //                                 .chipselect
		.NIOS_dm_agent_address                  (mm_interconnect_0_nios_dm_agent_address),               //                    NIOS_dm_agent.address
		.NIOS_dm_agent_write                    (mm_interconnect_0_nios_dm_agent_write),                 //                                 .write
		.NIOS_dm_agent_read                     (mm_interconnect_0_nios_dm_agent_read),                  //                                 .read
		.NIOS_dm_agent_readdata                 (mm_interconnect_0_nios_dm_agent_readdata),              //                                 .readdata
		.NIOS_dm_agent_writedata                (mm_interconnect_0_nios_dm_agent_writedata),             //                                 .writedata
		.NIOS_dm_agent_readdatavalid            (mm_interconnect_0_nios_dm_agent_readdatavalid),         //                                 .readdatavalid
		.NIOS_dm_agent_waitrequest              (mm_interconnect_0_nios_dm_agent_waitrequest),           //                                 .waitrequest
		.NIOS_timer_sw_agent_address            (mm_interconnect_0_nios_timer_sw_agent_address),         //              NIOS_timer_sw_agent.address
		.NIOS_timer_sw_agent_write              (mm_interconnect_0_nios_timer_sw_agent_write),           //                                 .write
		.NIOS_timer_sw_agent_read               (mm_interconnect_0_nios_timer_sw_agent_read),            //                                 .read
		.NIOS_timer_sw_agent_readdata           (mm_interconnect_0_nios_timer_sw_agent_readdata),        //                                 .readdata
		.NIOS_timer_sw_agent_writedata          (mm_interconnect_0_nios_timer_sw_agent_writedata),       //                                 .writedata
		.NIOS_timer_sw_agent_byteenable         (mm_interconnect_0_nios_timer_sw_agent_byteenable),      //                                 .byteenable
		.NIOS_timer_sw_agent_readdatavalid      (mm_interconnect_0_nios_timer_sw_agent_readdatavalid),   //                                 .readdatavalid
		.NIOS_timer_sw_agent_waitrequest        (mm_interconnect_0_nios_timer_sw_agent_waitrequest),     //                                 .waitrequest
		.RGBS_avalon_slave_0_address            (mm_interconnect_0_rgbs_avalon_slave_0_address),         //              RGBS_avalon_slave_0.address
		.RGBS_avalon_slave_0_write              (mm_interconnect_0_rgbs_avalon_slave_0_write),           //                                 .write
		.RGBS_avalon_slave_0_read               (mm_interconnect_0_rgbs_avalon_slave_0_read),            //                                 .read
		.RGBS_avalon_slave_0_readdata           (mm_interconnect_0_rgbs_avalon_slave_0_readdata),        //                                 .readdata
		.RGBS_avalon_slave_0_writedata          (mm_interconnect_0_rgbs_avalon_slave_0_writedata),       //                                 .writedata
		.RGBS_avalon_slave_0_chipselect         (mm_interconnect_0_rgbs_avalon_slave_0_chipselect),      //                                 .chipselect
		.SRAM_s1_address                        (mm_interconnect_0_sram_s1_address),                     //                          SRAM_s1.address
		.SRAM_s1_write                          (mm_interconnect_0_sram_s1_write),                       //                                 .write
		.SRAM_s1_readdata                       (mm_interconnect_0_sram_s1_readdata),                    //                                 .readdata
		.SRAM_s1_writedata                      (mm_interconnect_0_sram_s1_writedata),                   //                                 .writedata
		.SRAM_s1_byteenable                     (mm_interconnect_0_sram_s1_byteenable),                  //                                 .byteenable
		.SRAM_s1_chipselect                     (mm_interconnect_0_sram_s1_chipselect),                  //                                 .chipselect
		.SRAM_s1_clken                          (mm_interconnect_0_sram_s1_clken)                        //                                 .clken
	);

	Lab5_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios_platform_irq_rx_irq)        //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (nios_dbg_reset_out_reset),           // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
